title:              ESCape CTF Blog
email:              ESCape.ctf@gmail.com
description:        A Blog For CTF Write Up
author:             ESCape CTF Team
baseurl:            "/ESCape-CTF"
url:                "https://escape-ctf.github.io"

# Social Profiles
twitter_username:
github_username:    "ESCape-CTF"
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
